### ISSUE TITLE
Appending to incoming list

### ISSUE THREAD

**Issue by cowleyk** [nio-blocks/modifier#20]
I want to use a modifier block to create a new signal attribute that is an incoming list with a value appended to it.

I have an  incoming signal of `{ incoming_list = ['elem1', 'elem2'] }`
When I configure the block:
`Exclude existing fields: False`
`Attribute Name: append`
`Attribute Value: {{ $incoming_list.append('test') }}`
I see an output signal of `{ append: null, incoming_list: ['elem1', 'elem2', 'test'] }`

If I set `Exlude existing fields: True`
I see an output signal of `{ append: null }`
Rather than the expected `{ append: ['elem1', 'elem2', 'test'] }`

**Comment by mattdodge** [comment]
I think you want to do it like this:
```
{{ $incoming_list + ['test'] }}
```

**Comment by tlugger** [comment]
Much cleaner. That works great, thanks!
